## Task 1.1 Binary Classification - Merging

I divided the task into 3 notebooks, one to merge the datasets, another one to pre-process and finally one to classify the resulting dataset

In [15]:
# Required Python Packages
import pandas as pd
import numpy as np
import plotly.plotly as py
import plotly.graph_objs as go

 
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

import matplotlib.pyplot as plt
import seaborn as sns

/home/daniel/anaconda/envs/siemens/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning:

This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.

In [20]:
table1_dir = "tasks_siemens_data_lab/Training_part1.csv"
table2_dir = "tasks_siemens_data_lab/Training_part2.csv"
table_merged_dir = "dataset_merged.csv"
table1 = pd.read_csv(table1_dir,sep=';')
table2 = pd.read_csv(table2_dir,sep=';')
table1_clean = table1.drop_duplicates(subset='id',keep='first')
table2_clean = table2.drop_duplicates(subset='id',keep='first')
assert len(table1_clean) == len(table2_clean)
# Merge tables and index them by "id"
table_merged = table1_clean.merge(table2_clean, on='id')
table_merged_indexed = table_merged.set_index('id')
# Save resulting dataset into a csv to be used on another notebook 
table_merged_indexed.to_csv(table_merged_dir,index=False)

In [10]:
dataset = table_merged_indexed
training_features = ['BIB','COD','ERG','FAN','GJAH','LUK','MYR','NUS','PKD','RAS','SIS','TOK','UIN','VOL','WET','KAT','XIN']
target = 'Class'

In [7]:
table_merged_indexed

,BIB,COD,ERG,FAN,GJAH,LUK,MYR,NUS,PKD,RAS,SIS,TOK,UIN,VOL,WET,KAT,XIN,Class
id,,,,,,,,,,,,,,,,,,
0,160,iii,www,80.0,iii,5.0,eee,800000.0,xxx,t,1.750,t,17.92,f,1,ccc,t,n
1,153,uuu,aaa,200.0,rrr,0.0,mmm,2000000.0,xxx,NaN,0.290,f,16.92,f,0,ddd,f,n
2,5,iii,www,96.0,iii,19.0,hh,960000.0,hh,t,0.000,f,31.25,f,1,ddd,t,n
3,9,iii,www,0.0,iii,120.0,kkk,0.0,qqq,NaN,0.335,f,48.17,f,0,ccc,f,n
4,40,iii,www,232.0,iii,0.0,mmm,2320000.0,xxx,f,0.500,t,32.33,f,0,ddd,f,n
5,8,iii,aaa,160.0,rrr,0.0,kkk,1600000.0,jjj,f,0.500,t,34.83,f,0,ccc,f,n
6,152,iii,www,276.0,iii,1.0,lll,2760000.0,lll,NaN,0.000,t,26.17,f,0,ccc,f,n
7,176,iii,aaa,280.0,rrr,204.0,eee,2800000.0,jjj,NaN,0.250,f,21.17,f,0,ddd,f,n
8,154,iii,www,220.0,iii,140.0,eee,2200000.0,xxx,NaN,0.290,f,28.92,f,0,ddd,f,n
9,95,iii,www,320.0,iii,13.0,eee,3200000.0,jjj,NaN,1.085,f,18.17,f,0,ddd,f,n
10,121,iii,www,280.0,iii,1.0,sss,2800000.0,jjj,f,1.500,f,24.75,f,0,ccc,f,n
11,155,iii,aaa,160.0,rrr,20.0,lll,1600000.0,lll,f,0.000,f,31.75,f,0,ccc,f,n
12,91,iii,aaa,340.0,rrr,0.0,sss,3400000.0,jjj,f,0.165,f,18.17,f,0,ccc,f,n
13,91,iii,www,120.0,iii,1.0,yyy,1200000.0,xxx,NaN,1.000,f,18.25,f,1,ccc,t,n
14,91,iii,www,120.0,iii,1.0,yyy,1200000.0,jjj,t,0.165,f,17.58,f,1,ddd,t,n
15,19,iii,aaa,120.0,rrr,1.0,hh,1200000.0,hh,NaN,1.500,f,51.83,f,0,ddd,f,n
16,125,iii,www,178.0,iii,0.0,kkk,1780000.0,ff,f,0.000,t,26.67,f,0,ddd,f,n
17,128,iii,www,120.0,iii,0.0,eee,1200000.0,xxx,f,0.500,f,31.42,t,0,ddd,f,n
18,37,iii,www,416.0,iii,21.0,eee,4160000.0,jjj,t,2.290,t,25.67,f,1,ddd,t,n
19,31,iii,www,180.0,iii,0.0,kkk,1800000.0,ff,f,0.000,f,33.75,f,0,ddd,f,n
20,25,iii,www,292.0,iii,0.0,fff,2920000.0,jjj,f,5.750,t,32.75,f,0,ddd,f,n
21,164,uuu,www,288.0,iii,0.0,ooo,2880000.0,xxx,NaN,0.250,f,39.83,t,0,ddd,f,n
22,78,iii,aaa,NaN,rrr,18.0,mmm,NaN,xxx,NaN,0.165,f,40.33,f,2,ccc,t,n
23,131,iii,aaa,80.0,rrr,0.0,eee,800000.0,xxx,NaN,4.000,f,35.25,t,0,ddd,f,n
24,27,iii,aaa,200.0,rrr,456.0,kkk,2000000.0,ff,f,4.500,f,24.33,f,0,ccc,f,n
25,154,iii,www,120.0,iii,18.0,eee,1200000.0,xxx,f,1.000,f,15.75,f,0,ccc,f,n
26,50,uuu,www,240.0,iii,0.0,mmm,2400000.0,jjj,NaN,1.000,t,45.00,f,0,ccc,f,n
27,10,iii,www,0.0,iii,33.0,yyy,0.0,jjj,NaN,0.040,f,30.42,f,3,ccc,t,n
28,40,iii,www,300.0,iii,0.0,fff,3000000.0,xxx,NaN,3.000,t,NaN,t,0,ccc,f,n
29,155,iii,www,160.0,iii,40.0,mmm,1600000.0,xxx,NaN,0.040,t,17.25,f,0,ddd,f,n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3670,164,iii,www,280.0,iii,824.0,sss,2800000.0,jjj,NaN,1.500,f,24.50,t,0,ccc,f,y
3671,90,iii,www,0.0,iii,0.0,ggg,0.0,ff,NaN,0.000,f,20.25,t,0,ddd,f,y
3672,152,iii,www,120.0,iii,300.0,kkk,1200000.0,xxx,NaN,1.500,f,18.50,t,2,ddd,t,y
3673,40,iii,www,0.0,iii,7059.0,ee,0.0,xxx,t,0.625,f,25.17,t,7,ddd,t,y
3674,164,iii,www,320.0,iii,0.0,kkk,3200000.0,jjj,NaN,5.000,t,44.33,t,0,ddd,f,y
3675,60,iii,www,80.0,iii,0.0,mmm,800000.0,xxx,NaN,0.500,f,18.08,t,0,ddd,f,y
3676,131,iii,www,21.0,iii,10561.0,sss,210000.0,xxx,NaN,11.000,t,60.58,t,0,ccc,f,y
3677,13,iii,www,216.0,iii,0.0,kkk,2160000.0,ff,NaN,3.500,f,41.50,f,0,ddd,f,y
3678,164,iii,www,491.0,iii,0.0,eee,4910000.0,jjj,NaN,0.875,t,25.75,t,0,ccc,f,y
3679,126,iii,www,168.0,iii,0.0,ee,1680000.0,xxx,t,5.040,t,29.25,t,5,ddd,t,y
3680,147,iii,www,0.0,iii,456.0,eee,0.0,xxx,t,2.000,f,36.00,t,11,ccc,t,y
3681,130,iii,www,250.0,iii,730.0,fff,2500000.0,xxx,t,3.000,f,31.67,t,9,ddd,t,y
3682,124,iii,www,0.0,iii,1000.0,hh,0.0,hh,t,18.000,t,60.08,t,15,ddd,t,y
3683,101,iii,www,80.0,iii,278.0,yyy,800000.0,xxx,NaN,2.000,f,22.33,t,1,ddd,t,y
3684,68,iii,www,0.0,iii,500.0,ee,0.0,ff,NaN,3.500,f,40.00,t,1,ddd,t,y
3685,140,iii,www,515.0,iii,500.0,zzz,5150000.0,jjj,NaN,1.625,t,35.17,t,1,ddd,t,y
3686,1,iii,www,0.0,iii,0.0,eee,0.0,ff,NaN,15.000,f,41.33,t,0,ddd,f,y
3687,97,iii,www,80.0,iii,50.0,ee,800000.0,jjj,t,0.335,t,20.75,t,1,ccc,t,y
3688,158,iii,www,360.0,iii,0.0,ooo,3600000.0,xxx,NaN,2.500,t,32.08,t,0,ddd,f,y
3689,158,iii,www,290.0,iii,2279.0,zzz,2900000.0,xxx,t,5.000,t,NaN,t,3,ddd,t,y
3690,12,iii,www,200.0,iii,327.0,fff,2000000.0,jjj,t,1.875,f,23.92,t,6,ddd,t,y
3691,65,iii,www,120.0,iii,245.0,sss,1200000.0,xxx,NaN,3.170,f,23.25,t,10,ccc,t,y
3692,157,iii,www,440.0,iii,6.0,ee,4400000.0,jjj,NaN,0.415,t,46.67,t,11,ccc,t,y
3693,113,iii,www,400.0,iii,458.0,ee,4000000.0,jjj,t,3.500,f,25.00,t,6,ccc,t,y
3694,154,iii,www,260.0,iii,15108.0,ooo,2600000.0,xxx,t,0.250,f,25.50,t,3,ddd,t,y
3695,74,iii,www,NaN,iii,26726.0,sss,NaN,xxx,t,2.710,f,18.75,t,5,ccc,t,y
3696,179,iii,www,120.0,iii,0.0,sss,1200000.0,xxx,t,8.500,t,23.50,t,5,ccc,t,y
3697,82,iii,www,0.0,iii,221.0,eee,0.0,xxx,NaN,4.500,t,34.17,t,12,ddd,t,y
3698,13,iii,www,100.0,iii,3.0,yyy,1000000.0,xxx,NaN,3.750,t,27.83,t,5,ddd,t,y
3699,57,iii,www,0.0,iii,4000.0,ggg,0.0,xxx,f,5.000,t,36.75,t,0,ccc,f,y

In [11]:
def unique_observations(dataset, header, method=1):
    """
    To get unique observations in the loaded pandas DataFrame column
    :param dataset:
    :param header:
    :param method: Method to perform the unique (default method=1 for pandas and method=0 for numpy )
    :return:
    """
    try:
        if method == 0:
            # With Numpy
            observations = np.unique(dataset[[header]])
        elif method == 1:
            # With Pandas
            observations = pd.unique(dataset[header].values.ravel())
        else:
            observations = None
            print("Wrong method type, Use 1 for pandas and 0 for numpy")
    except Exception as e:
        observations = None
        print("Error: {error_msg} /n Please check the inputs once..!".format(error_msg=e.message))
    return observations


def feature_target_frequency_relation(dataset, f_t_headers):

    """
    To get the frequency relation between targets and the unique feature observations
    :param dataset:
    :param f_t_headers: feature and target header
    :return: feature unique observations dictionary of frequency count dictionary
    """

    feature_unique_observations = unique_observations(dataset, f_t_headers[0])
    unique_targets = unique_observations(dataset, f_t_headers[1])

    frequencies = {}
    for feature in feature_unique_observations:
        frequencies[feature] = {unique_targets[0]: len(
            dataset[(dataset[f_t_headers[0]] == feature) & (dataset[f_t_headers[1]] == unique_targets[0])]),
            unique_targets[1]: len(
                dataset[(dataset[f_t_headers[0]] == feature) & (dataset[f_t_headers[1]] == unique_targets[1])])}
    return frequencies


def feature_target_histogram(feature_target_frequencies, feature_header):
    """
    
    :param feature_target_frequencies: 
    :param feature_header: 
    :return: 
    """
    keys = list(feature_target_frequencies.keys())
    y0 = [feature_target_frequencies[key]['y'] for key in keys]
    y1 = [feature_target_frequencies[key]['n'] for key in keys]

    
    trace1 = go.Bar(
        x=keys,
        y=y0,
        name='y'
    )
    trace2 = go.Bar(
        x=keys,
        y=y1,
        name = 'n'
    )
 
    data = [trace1, trace2]
    layout = go.Layout(
        barmode='group',
        title='Feature :: ' + feature_header + ' yes vs no',
        xaxis=dict(title="Feature :: " + feature_header + " classes"),
        yaxis=dict(title="Class Frequency")
    )
    fig = go.Figure(data=data, layout=layout)

    fig = go.Figure(data=data)
    # plot_url = py.plot(fig, filename=feature_header + ' - Target - Histogram')
    py.image.save_as(fig, filename=feature_header + '_Target_Histogram.png')

From the dataset, one can acknowladge a mix of variables:
BIB, FAN, LUK, NUS, SIS, UIN - Numerical Variables
COD, ERG, GJAH, MYR, PKD, RAS, TOK,VOLD, KAT - Categorical Variables
Xin - Binary Variable (TOK can also be considered 
Class - Target Variable
The data set has 3700 rows and 18 columns.

Before pre-process and analyse the data, one can look into the histograms for a deeper insight, in the next loop we build all histograms refering to each variable on the dataset.

In [13]:
for feature in training_features:
    feature_target_frequencies = feature_target_frequency_relation(dataset, [feature, target])
    feature_target_histogram(feature_target_frequencies, feature)

For example, bellow we can see the COD Histogram, all atributes are highly correlated, giving a positive classification (Class = y) for any attribute

<img src="COD_Target_Histogram.png">

Another example of high correlation can be seen in the TOK variable, where, regardless of any of the two attributes, we get the same proportion classification targets.

<img src="TOK_Target_Histogram.png">

In the next notebook, proposes to pre-process the dataset are made in order to clean and make it feasible to train on a classifier.

In [19]:
!jupyter nbconvert Task\ 1\ Binary\ Classification\ -\ Merging.ipynb --to html

[NbConvertApp] Converting notebook Task 1 Binary Classification - Merging.ipynb to html
[NbConvertApp] Writing 296743 bytes to Task 1 Binary Classification - Merging.html